pub mod anime;
mod anime_in_anime_list;
mod anime_list;
pub mod arguments;
pub mod config;
pub mod error;
mod genre;
pub mod roles;
pub mod season;
pub mod source;
pub mod source_type;
mod title;
mod title_type;
pub mod user;
